package com.harrisburg.entity;
// Generated Feb 25, 2019 6:49:50 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable {
	private Product Product;
	private ProductOrder ProductOrder;
	
	public OrderDetailId() {
		
	}

	public OrderDetailId(Product Product, ProductOrder ProductOrder) {
		this.Product = Product;
		this.ProductOrder = ProductOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_id", insertable = false, updatable = false, nullable = false)
	public Product getProduct() {
		return this.Product;
	}

	public void setProduct(Product Product) {
		this.Product = Product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", insertable = false, updatable = false, nullable = false)
	public ProductOrder getProductOrder() {
		return this.ProductOrder;
	}

	public void setProductOrder(ProductOrder ProductOrder) {
		this.ProductOrder = ProductOrder;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((Product == null) ? 0 : Product.hashCode());
		result = prime * result + ((ProductOrder == null) ? 0 : ProductOrder.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderDetailId other = (OrderDetailId) obj;
		if (Product == null) {
			if (other.Product != null)
				return false;
		} else if (!Product.equals(other.Product))
			return false;
		if (ProductOrder == null) {
			if (other.ProductOrder != null)
				return false;
		} else if (!ProductOrder.equals(other.ProductOrder))
			return false;
		return true;
	}
	

}
