package com.harrisburg.entity;
// Generated Feb 25, 2019 6:49:50 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail", catalog = "Productstoredb")
@NamedQueries({
	@NamedQuery(name = "OrderDetail.countByProduct",
			query = "SELECT COUNT(*) FROM OrderDetail od WHERE od.Product.ProductId =:ProductId"),
	@NamedQuery(name = "OrderDetail.bestSelling",
			query = "SELECT od.Product FROM OrderDetail od GROUP BY od.Product.ProductId"
					+ " ORDER BY SUM(od.quantity) DESC")
})
public class OrderDetail implements java.io.Serializable {

	private OrderDetailId id = new OrderDetailId();
	private Product Product;
	private ProductOrder ProductOrder;
	private int quantity;
	private float subtotal;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId id) {
		this.id = id;
	}

	public OrderDetail(int quantity, float subtotal, OrderDetailId id, Product Product, ProductOrder ProductOrder) {
		this.id = id;
		this.quantity = quantity;
		this.subtotal = subtotal;
		this.Product = Product;
		this.ProductOrder = ProductOrder;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "ProductId", column = @Column(name = "Product_id", nullable = false))
	})
	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "subtotal", nullable = false, precision = 12, scale = 0)
	public float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Product_id", insertable = false, updatable = false, nullable = false)
	public Product getProduct() {
		return this.Product;
	}

	public void setProduct(Product Product) {
		this.Product = Product;
		this.id.setProduct(Product);
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", insertable = false, updatable = false, nullable = false)
	public ProductOrder getProductOrder() {
		return this.ProductOrder;
	}

	public void setProductOrder(ProductOrder ProductOrder) {
		this.ProductOrder = ProductOrder;
		this.id.setProductOrder(ProductOrder);
	}

}
